---
resolution:
    x: 1920
    y: 1080
machines:
    - name: genesis
      logo: megadrive.png
      emus: dgen

    - name: snes
      logo: snes.png
      emus: 
        - name: zsnes
          path: /opt/zsnes
